version: "3.8"

services:
    postgres:
        image: postgres:14
        container_name: salary_postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: salary_management
        volumes:
            - postgres_data:/var/lib/postgresql/data

    app:
        build: .
        container_name: salary_app
        restart: always
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            - postgres

volumes:
    postgres_data:
